// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.20.3
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package generators

import (
	annotations "github.com/YReshetko/go-annotation/annotations/validator/annotations"
	model "github.com/YReshetko/go-annotation/annotations/validator/model"
	annotation "github.com/YReshetko/go-annotation/pkg"
	ast "go/ast"
)

func NewGenerator(node annotation.Node, ts *ast.TypeSpec, va annotations.Validator) Generator {
	returnValue := Generator{
		node: node,
		ts:   ts,
		va:   va,
	}
	returnValue.postConstruct()

	return returnValue
}

func NewOutput(v model.Validatable) Output {
	returnValue := Output{
		v: v,
	}

	return returnValue
}
