// Code generated by Rest annotation processor. DO NOT EDIT.
// versions:
//		go: go1.18.3
//		go-annotation: 0.1.0
//		Rest: 0.0.1
package handlers

import (
	"net/http"
)

func (s *Container) Handlers() map[string]http.HandlerFunc {
	return map[string]http.HandlerFunc{
		http.MethodGet:    s.getContainer,
		http.MethodPatch:  s.patchContainer,
		http.MethodDelete: s.deleteContainer,
	}
}

func (s *Container) Path() string {
	return "/api/v1/containers/{container_id}"
}
