// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.18.3
//		go-annotation: 0.0.19
//		Constructor: 1.0.0

package cache

func NewImportCache(aliasTpl string) *ImportCache {
	returnValue := &ImportCache{
		aliasTpl:    aliasTpl,
		baseImports: make(map[Import]struct{}),
		imports:     make(map[Import]AliasItem),
	}

	return returnValue
}
