// Code generated by Mock annotation processor. DO NOT EDIT.
// versions:
//		go-annotation: 0.0.2-alpha
//		Mock: 0.0.1
// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"net/http"
	"sync"

	"github.com/YReshetko/go-annotation/examples/mock/internal/parametrized"
)

type ParametrizedFuncMock struct {
	Stub        func(*http.Request) []*http.Request
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 *http.Request
	}
	returns struct {
		result1 []*http.Request
	}
	returnsOnCall map[int]struct {
		result1 []*http.Request
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ParametrizedFuncMock) Spy(arg1 *http.Request) []*http.Request {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 *http.Request
	}{arg1})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("ParametrizedFuncMock", []interface{}{arg1})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return returns.result1
}

func (fake *ParametrizedFuncMock) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *ParametrizedFuncMock) Calls(stub func(*http.Request) []*http.Request) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *ParametrizedFuncMock) ArgsForCall(i int) *http.Request {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1
}

func (fake *ParametrizedFuncMock) Returns(result1 []*http.Request) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 []*http.Request
	}{result1}
}

func (fake *ParametrizedFuncMock) ReturnsOnCall(i int, result1 []*http.Request) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 []*http.Request
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 []*http.Request
	}{result1}
}

func (fake *ParametrizedFuncMock) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ParametrizedFuncMock) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ parametrized.ParametrizedFuncMock = new(ParametrizedFuncMock).Spy
