// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go-annotation: 0.0.2-alpha
//		Constructor: 0.0.3

package utils

func NewNode[K comparable, V any]() *Node[K, V] {
	returnValue := &Node[K, V]{
		key:   []K{},
		value: []V{},
		nodes: make(map[K]*Node[K, V]),
	}

	return returnValue
}
