// Code generated by CGS annotation processor. DO NOT EDIT.
// versions:
//		go-annotation: 0.0.2-alpha
//		CGS: 0.0.1
package internal

func NewSomeStructureOverride(a int, b float64, c *bool, d **complex128) SomeStructure {
	return SomeStructure{
		a: a,
		b: b,
		c: c,
		d: d,
	}
}

func NewAnotherStructOverride(d int, fn func(**SomeStructure) AnotherStruct, a SomeStructure, b *SomeStructure, c int) *AnotherStruct {
	return &AnotherStruct{
		d:  d,
		fn: fn,
		a:  a,
		b:  b,
		c:  c,
	}
}
