// Code generated by Mock annotation processor. DO NOT EDIT.
// versions:
//		go: go1.18.3
//		go-annotation: 0.0.4-alpha
//		Mock: 0.0.1
// Code generated by counterfeiter. DO NOT EDIT.
package pkg_mocks

import (
	"net/http"

	"github.com/YReshetko/go-annotation/examples/mock/internal/handlers"
)

//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 -generate
//counterfeiter:generate . HandlersMock

// HandlersMock is a generated interface representing the exported functions
// in the github.com/YReshetko/go-annotation/examples/mock/internal/handlers package.
// Injected annotations: @Mock(sub="mocksfakes")
type HandlersMock interface {
	DoSomeAnother(arg1 http.Response)
	DoSomething(arg1 http.Request)
}

type HandlersMockShim struct{}

func (p *HandlersMockShim) DoSomeAnother(arg1 http.Response) {
	handlers.DoSomeAnother(arg1)
}

func (p *HandlersMockShim) DoSomething(arg1 http.Request) {
	handlers.DoSomething(arg1)
}

var _ HandlersMock = new(HandlersMockShim)
